# Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
servers:
  -
    hostname: mysql
    box: mysql
    ip: 172.28.128.3
    ram: 2048
    cpu: 1
    provisioner_script: mysql/provisioner/db_provisioner.sh
  -
    hostname: identity-server
    box: wso2is
    ip: 172.28.128.4
    ports:
      - 9443
    ram: 2048
    cpu: 1
    provisioner_script: identity-server/provisioner/product_provisioner.sh
  -
    hostname: identity-server-analytics
    box: wso2is-analytics
    ip: 172.28.128.5
    ports:
      - 9444
    ram: 2048
    cpu: 1
    provisioner_script: identity-server-analytics/provisioner/product_provisioner.sh
